import createFetchClient from "openapi-fetch"
import createClient from "openapi-react-query"
import type { paths } from "@/lib/panoptikon" // generated by openapi-typescript

export const fetchClient = createFetchClient<paths>({
  baseUrl: "/",
})
// Server-side fetches live in lib/serverApi.ts: they read the incoming
// request's policy token via next/headers, which must not be imported from
// this module (it is bundled into client components).
export const $api = createClient(fetchClient)
