"use client"

import createFetchClient from "openapi-fetch"
import createClient from "openapi-react-query"
import type { paths } from "@/lib/panoptikon" // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: "/",
})
export const $api = createClient(fetchClient)
