export const PLACEHOLDERS = [
  "What do you want to find today?",
  "What are you searching for?",
  "Find what you're looking for.",
  "What will you discover today?",
  "Search your next adventure.",
  "Looking for something?",
  "Explore new ideas.",
  "What’s on your mind?",
  "Search your journey.",
  "Find your inspiration.",
  "Seek, and you shall find!",
  "Get your search on!",
  "Uncover what clicks today.",
  "Go ahead, make a query.",
  "Finders, seekers!",
  "On the hunt? Start here.",
  "Let’s search and rescue that info.",
  "Your quest begins here.",
  "Navigate your way to answers.",
  "Discover the unknown.",
  "Search for the truth.",
  "Find the needle in the haystack.",
  "Search for the key to success.",
  "Find the missing piece.",
  "Search for the golden ticket.",
  "Seek and you shall find.",
  "Search for the moon, reach the stars.",
  "Five Nights at Pano’s.",
] as const
